service: order-reactor

package:
  exclude:
    - ./**
  include:
    - ./bin/**

provider:
  name: aws
  accountId: ${env:AWS_ACCOUNT_ID}
  runtime: go1.x
  stage: ${env:APP_STAGE}
  stackName: ${self:service}-${self:provider.stage}
  region: ap-southeast-1
  memorySize: 1024
  logRetentionInDays: 7
  iamRoleStatements:
    - Effect: 'Allow'
      Resource: '*'
      Action:
        - 'dynamodb:*'

functions:
  service:
    handler: bin/app
    events:
      - stream: arn:aws:dynamodb:ap-southeast-1:805785015849:table/eventstore/stream/2019-02-02T10:27:19.969
    environment:
      APP_DYNAMODB_ENDPOINT: ${env:APP_DYNAMODB_ENDPOINT}
