// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gocqrs "github.com/onedaycat/gocqrs"
import mock "github.com/stretchr/testify/mock"

// EventStore is an autogenerated mock type for the EventStore type
type EventStore struct {
	mock.Mock
}

// GetAggregate provides a mock function with given fields: aggID, agg
func (_m *EventStore) GetAggregate(aggID string, agg gocqrs.AggregateRoot) error {
	ret := _m.Called(aggID, agg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, gocqrs.AggregateRoot) error); ok {
		r0 = rf(aggID, agg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEvents provides a mock function with given fields: aggID, seq, agg
func (_m *EventStore) GetEvents(aggID string, seq int64, agg gocqrs.AggregateRoot) ([]*gocqrs.EventMessage, error) {
	ret := _m.Called(aggID, seq, agg)

	var r0 []*gocqrs.EventMessage
	if rf, ok := ret.Get(0).(func(string, int64, gocqrs.AggregateRoot) []*gocqrs.EventMessage); ok {
		r0 = rf(aggID, seq, agg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gocqrs.EventMessage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int64, gocqrs.AggregateRoot) error); ok {
		r1 = rf(aggID, seq, agg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsByAggregateType provides a mock function with given fields: aggType, seq
func (_m *EventStore) GetEventsByAggregateType(aggType string, seq int64) ([]*gocqrs.EventMessage, error) {
	ret := _m.Called(aggType, seq)

	var r0 []*gocqrs.EventMessage
	if rf, ok := ret.Get(0).(func(string, int64) []*gocqrs.EventMessage); ok {
		r0 = rf(aggType, seq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gocqrs.EventMessage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int64) error); ok {
		r1 = rf(aggType, seq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsByEventType provides a mock function with given fields: eventType, seq
func (_m *EventStore) GetEventsByEventType(eventType string, seq int64) ([]*gocqrs.EventMessage, error) {
	ret := _m.Called(eventType, seq)

	var r0 []*gocqrs.EventMessage
	if rf, ok := ret.Get(0).(func(string, int64) []*gocqrs.EventMessage); ok {
		r0 = rf(eventType, seq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gocqrs.EventMessage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int64) error); ok {
		r1 = rf(eventType, seq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSnapshot provides a mock function with given fields: aggID, agg
func (_m *EventStore) GetSnapshot(aggID string, agg gocqrs.AggregateRoot) error {
	ret := _m.Called(aggID, agg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, gocqrs.AggregateRoot) error); ok {
		r0 = rf(aggID, agg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: agg
func (_m *EventStore) Save(agg gocqrs.AggregateRoot) error {
	ret := _m.Called(agg)

	var r0 error
	if rf, ok := ret.Get(0).(func(gocqrs.AggregateRoot) error); ok {
		r0 = rf(agg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetEventLimit provides a mock function with given fields: limit
func (_m *EventStore) SetEventLimit(limit int64) {
	_m.Called(limit)
}

// SetSnapshotStrategy provides a mock function with given fields: strategies
func (_m *EventStore) SetSnapshotStrategy(strategies gocqrs.SnapshotStategyHandler) {
	_m.Called(strategies)
}
